---
- name: Set the wal_level to logical
  community.postgresql.postgresql_set:
    db: '{{ postgres_db }}'
    login_host: '{{ postgres_host }}'
    port: '{{ postgres_port }}'
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: wal_level
    value: "logical"

- name: Create a user for OSO
  community.postgresql.postgresql_user:
    db: '{{ postgres_db }}'
    login_host: '{{ postgres_host }}'
    port: '{{ postgres_port }}'
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: '{{ postgres_oso_user_name }}'
    password: '{{ postgres_oso_user_password }}'
    expires: '{{ postgres_oso_user_expiration }}'
    role_attr_flags: 'REPLICATION'
    state: present

- name: Create a logical replication slot to the database 
  community.postgresql.postgresql_slot:
    db: '{{ postgres_db }}'
    login_host: '{{ postgres_host }}'
    port: '{{ postgres_port }}'
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: '{{ postgres_oso_replication_slot_name }}'
    slot_type: logical
    state: present
    output_plugin: pgoutput

- name: Create a new publication for all the specified tables
  community.postgresql.postgresql_publication:
    db: '{{ postgres_db }}'
    login_host: '{{ postgres_host }}'
    port: '{{ postgres_port }}'
    login_user: '{{ postgres_user }}'
    login_password: '{{ postgres_password }}'
    name: '{{ postgres_oso_publication_name }}'
    tables: '{{ postgres_oso_publication_tables }}'
    state: present
