apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagster
spec:
  values:
    global:
      serviceAccountName: base-dagster
    configMap:
      secretPrefix: "gcp:secretmanager:production-dagster"
    dagster:
      global: 
        serviceAccountName: production-dagster