apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-daemon
  namespace: production-dagster
spec:
  template:
    spec:
      initContainers:
        - name: check-db-ready
          envFrom:
            - configMapRef:
                name: dagster-oso-extra-env
