apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dagster
spec:
  template:
    spec:
      initContainers:
        - name: check-db-ready
          envFrom:
            - configMapRef:
                name: dagster-oso-extra-env
