apiVersion: cloudsql.cloud.google.com/v1
kind: AuthProxyWorkload
metadata:
  name: dagster-auth-proxy
spec:
  authProxyContainer:
    resources:
      requests:
        cpu: "1"
        memory: "500Mi"
  workloadSelector:
    kind: "Deployment" # Applies to a "Deployment"
    name: dagster-daemon
  instances:
    - connectionString: "opensource-observer:us-central1:oso-psql"
      portEnvName: "DAGSTER_PG_PORT"
      hostEnvName: "DAGSTER_PG_HOST"