name: PR Sync

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

permissions: write-all

jobs:
  prsync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/DataRecce/github-pr-syncer.git

    - name: Set up Git
      run: |
        git config --global user.name "prsync[bot]"
        git config --global user.email "prsync[bot]@users.noreply.github.com"

    - name: Run pysync
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # We meed the "workflows" permission which teh github token for job cannot provide. Use the PersonalAccessToken instead.
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_ADVANCED_PERMISSIONS }}    
      run: |
        prsync 'DataRecce/oso'
