name: PR Sync

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

jobs:
  run_pysync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/DataRecce/github-pr-syncer.git

    - name: Run pysync
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      run: |
        prsync 'DataRecce/oso'
